language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - source
script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$github_token"
  local-dir: dist
  target-branch: master
  committer-from-gh: true
  verbose: true
  fqdn: https://www.umstek.tk/js-timer/
  on:
    branch: source
env:
  global:
  - secure: XZ1hdIIE9EC6Xwfzb/bMsF9pxa5L4KOMm1oUL+cN/0J27ozmeC8djcqVfHbMAP98CYpsdm2TJGVKpqQSxWPLFpOcrTcDQRu4X53V/uOzLqaejbL6nZqHKz+Eimw+8n2H5gI1T39WiTfjoc3fP88HpFuNU5UYqomuLN2Zzx4UE0YjYSPpRm+UW2d0YVSKsjLqF+ltZQdW61PYU4j/meoxfWe4hD0Gkev6PWO4N4P5loyx+vZps0deMehZ3gTIlr9wuQJ23xUF+DHyBpvmbgjGY2tA3xqKAxJgZCCVa6nuZZwweMAs8NRfrqGc3ov67byD3zMu+Ly3a8xoGy7mvogNmZcHWJXRDqFbxnh4KtdtLnBVqTYs94GGUqqX5iI6aJWPAu1FzISJB7wN+8rWC9iJ0e6IAHWNx1K1wRQ3QcyUa+2tJlj1D9PuoXyrN/trdPCVv1rmWp3ChMCeFVh+gGhuuLItlTZH13dMSBAhL9n6tu6O0yalMJvP3jRWpmCwfpWvho0w8YfonKtQBCUsxpxOoH4pd7mfnEvZjDEh/r4uEDes7v/5RyHbpAM8PVFBRGT0EjZq9jxOoVl9C/wZUXOFTQmaqfWnMsC58Oyplp93lNSudVkMakM/08MPR+NGcDyYk696bQXz2ThXK6dkTVv8EamMR2ZV6gujGXJ7cSPv1Ys=
