language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - source
script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_Key"
  local-dir: dist
  target-branch: master
  committer-from-gh: true
  verbose: true
  fqdn: https://www.umstek.tk/js-timer/
  on:
    branch: source
env:
  global:
    secure: cXVW9wWkC/6nAaxWGpSt8cC5+LzWJNxRL2AzgcmTa2uKstLvcxaOEZsUT8VS55XglxvfMMs7itxNf4YbomWNZ26kSwAEDhNBvrdq+QldKvD+wgkdD6IjFJ32VxIUMnPSBjp0PuUiaK1hnoT7CMr5N2Foh/vJ2HS3ScnGjIknpOTGgD26jgSx/wV6PcwC00WZoJONShYEMPazUD6s3ucuQX/VZ4iNesSNtcFYVMakmx3FxttUN+dtO2EJAoDWjszhLLa+grRol/HmAKsBEQd/J2jDXkVIrauIxV7DDmFJ04wMjNRuBVZ1qeHdxtl3EHMqN3DSUezESYGm05/r+HKy4O+Ike/fmCGKG8RmRVcSTv1UYaAluYvNElBerMuEj14AfWJC8yjsVVR8z5tPtP3jiwgO1+FDSkNago5uHx5c8zfhCBpkszQ5v6cGPaqqZlIPBY+0WOhbw4ypz+9kdpYIUwJ0Hq5zMsR+i+C//CUvNKNRdwmLySiEB8FzYIDG2JZbbR8QyG98tkyVjypcBLWTt0EgLMz5fjYmPIaLO3cu4UN47ymasXGCsIzxNndF2z+VF17qoeLVs0jI3UToPpltU25foorVQlbExwK65JCpNLyJWZFb6jOyPejQEjBwME9OJ4zberzHtlgdCv4gzC/SAYGgVWmXwQVf1gpgPFqBpEU=
